# Generated by Django 5.0.3 on 2024-03-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=200)),
                ('vendorname', models.CharField(db_index=True, max_length=200, unique=True)),
                ('joiningdate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('vendorcontact', models.CharField(db_index=True, max_length=14)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMilkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200)),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerMilkCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customerledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=1000000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('quantity', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('total', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to=settings.AUTH_USER_MODEL)),
                ('related_milk_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to='dairy.customermilkcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Manager', 'Manager')], max_length=20, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True, unique=True)),
                ('joining_data', models.DateField()),
                ('address', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user_type',),
            },
        ),
        migrations.CreateModel(
            name='MilkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200)),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
                ('related_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MilkCategory', to='dairy.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='vendorledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=1000000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('quantity', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('total', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('related_milkcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairy.milkcategory')),
                ('related_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairy.vendor')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
